name: "Schedule - Check links"
on: # yamllint disable-line rule:truthy
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
# yamllint disable rule:line-length
jobs:
  link-checker:
    name: Link Checker
    runs-on: ubuntu-latest
    if: github.repository == 'SovereignCloudStack/csctl'
    steps:
      - name: Checkout
        uses: actions/checkout@93cb6efe18208431cddfb8368fd83d5badbf9bfd # v5.0.1

      - name: Generate Token
        uses: tibdex/github-app-token@3beb63f4bd073e61482598c45c71c1019b59b73a # v2
        id: generate-token
        with:
          app_id: ${{ secrets.SCS_APP_ID }}
          private_key: ${{ secrets.SCS_APP_PRIVATE_KEY }}

      - name: Link Checker
        uses: lycheeverse/lychee-action@f613c4a64e50d792e0b31ec34bbcbba12263c6a6 # v2.3.0
        id: lychee
        env:
          GITHUB_TOKEN: "${{ steps.generate-token.outputs.token }}"
        with:
          args: --config .lychee.toml ./*.md  ./docs/**/*.md
          output: ./lychee.md
          format: markdown

      - name: Find Link Checker Issue
        id: link-checker-issue
        uses: micalevisk/last-issue-action@0d40124cc99ac8601c2516007f0c98ef3d27537b # v2
        with:
          state: open
          labels: |
            link-checker

      - name: Update Issue
        uses: peter-evans/create-issue-from-file@e8ef132d6df98ed982188e460ebb3b5d4ef3a9cd # v5
        with:
          title: Link Checker Dashboard
          issue-number: "${{ steps.link-checker-issue.outputs.issue_number }}"
          content-filepath: ./lychee.md
          token: "${{ steps.generate-token.outputs.token }}"
          labels: |
            link-checker
